services:
  leisaac-debug:
    build:
      context: .
      dockerfile: Dockerfile
    image: leisaac-server:latest
    container_name: leisaac-server
    runtime: nvidia
    network_mode: host
    # ports:
    #   - "8011:8011/tcp"
    #   - "48010:48010/tcp"
    #   - "49100:49100/tcp"
    #   - 47998-48020:47998-48020/udp"
    ipc: host
    stdin_open: true
    tty: true
    working_dir: /workspace/repo
    environment:
      LEISAAC_ASSETS_ROOT: /workspace/repo/assets
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - .:/workspace/repo
      - /etc/vulkan/icd.d:/etc/vulkan/icd.d:ro
    ulimits:
      memlock: -1
      stack: 67108864
    command:
      - uv
      - run
      - scripts/environments/teleoperation/teleop_se3_agent.py
      - --task=LeIsaac-SO101-PickOrange-v0
      - --teleop_device=so101leader
      - --remote_endpoint=tcp://10.10.40.254:5556
      - --num_envs=1
      - --device=cuda
      - --enable_cameras
      - --headless
      - --livestream=2
